[workspace]
members = [
    "."
]

[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
anchor_vrf_parser = "2NrzAhEHfvyqknfQ6oSC4i3cGmxPRSpa5g3oWWWVWVtd"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/*.test.ts"

[test.validator]
url="https://api.devnet.solana.com"

